apiVersion: v1
kind: ServiceMonitor
metadata:
  name: sup-monitoring
  namespace: sup
  labels:
    app: sup
    monitoring: enabled
spec:
  selector:
    matchLabels:
      monitoring: enabled
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sup-network-policy
  namespace: sup
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        - namespaceSelector:
            matchLabels:
              name: monitoring
        - podSelector: {}
  egress:
    - to: []
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to:
        - podSelector: {}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: sup
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: autocomplete-pdb
  namespace: sup
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: autocomplete
