version: '3.8'

services:
  spam-detection:
    build: .
    ports:
      - "8003:8003"
    environment:
      - REDIS_URL=redis://localhost:6379
      - LOG_LEVEL=DEBUG
      - RELOAD=true
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./config:/app/config
      - .:/app
    command: uvicorn api_server:app --host 0.0.0.0 --port 8003 --reload
    networks:
      - spam-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - spam-net

volumes:
  redis_data:

networks:
  spam-net:
    driver: bridge
